spring:
  application:
    name: jootodo
  security:
    user:
      name: youssef
  web:
    resources:
      add-mappings: false

  datasource:
    url: jdbc:postgresql://localhost:5432/todoapp
    username: postgres
    password: 1311022000
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 2025